jetstore-tools/jetrule-grammar/jet_listener.py
jetstore-tools/jetrule-grammar/jet_listener_postprocessing_test.py
jetstore-tools/jetrule-grammar/jet_listener_postprocessing_test2.py
jetstore-tools/jetrule-grammar/jet_listener_postprocessing_test_data.jr.json
jetstore-tools/jetrule-grammar/jet_listener_test.py
jetstore-tools/jetrule-grammar/jet_listerner_test_data.jr.json
jetstore-tools/jetrule-grammar/jetrule_compiler.py
jetstore-tools/jetrule-grammar/jetrule_context.py

Adjustments and fixes on JetRule validation

---

jets/rete/rete_meta_store_factory.cc
jets/server/pipeline.go
jets/server/workspace.go

Jetstore server: Load process rules and process config

---

Dockerfile.go_bullseye
Dockerfile.rt_bullseye
docker_notes.md

Bug: Add db update to the docker image

---

go.mod
go.sum
jets/server/pipeline.go
jets/server/rete.go

Bug: Identify nulls in input table

---

jets/bridge/bridge.go
jets/bridge/bridge_test.go
jets/rdf/r_manager.h
jets/rdf/rdf_ast.h
jets/rdf/rdf_ast_test.cc
jets/rdf/rdf_date_time.cc
jets/rete/jets_rete_cwrapper.cpp

Bug: Invalid date crashes the server

---

docker_notes.md
jets/server/pipeline.go
jets/server/process_config.go
jets/server/process_schema.sql
jets/server/rete.go

JetStore Server: Add input table column name to process_errors table

---

jets/server/rete_input.go

Bug: reformat0 taking first 5 digit by mistake

---

jets/rete/rete_session.cc

Bug: server crash in test due to dependency of RdfSession by ReteSession

---

jets/server/pipeline.go
jets/server/test_data/process_config_test2.sql
jets/workspace/workspace.go

Bug: Server hangs when not writing to all tables of workspace

---

.github/workflows/jetstore_image_build.yml

Re enabled compiler python test

reenabled compiler test

---

go.mod

fix security issue gopkg.in/yaml.v3

---

.gitignore
jets/compiler/jetrule_rete.py
jets/compiler/jetrule_rete_sqlite.py
jets/server/test_data/test5_ruleset1.jr

New fix on beta var ordering

---

jets/CMakeLists.txt
jets/rdf/r_resources.cc
jets/rdf/r_resources.h
jets/rete/expr_op_arithmetics.h
jets/rete/expr_op_specialty_test.cc

Bug: sorted_head operator is returning the value not the subject

---

jets/server/pipeline.go
jets/server/process_config.go
jets/server/rete.go
jets/server/rete_entity.go
jets/server/rete_input.go
jets/server/server.go
jets/server/table_reader.go
jets/update_db/update_db.go

JetStore Server merge multiple input source

---

jets/server/rete.go

Bug: New build broke input assertion in sequence

---

jets/loader/loader.go
jets/loader/test_data/err_test4.csv
jets/loader/test_data/test4.csv

Add sharding to jetstore loader command

---

jets/loader/loader.go

JetStore: make first db node as primary node of cluster

---

jets/loader/loader.go

Shard input file using the grouping column when provided

---

jets/loader/loader.go
jets/loader/test_data/test3.csv
jets/loader/test_data/test4.csv

Bug: Loader mishandle the header position when column must be skipped

---

jets/apiserver/api.go
jets/apiserver/token.go
jetsclient/lib/main.dart
jetsclient/lib/models/user.dart
jetsclient/lib/routes/export_routes.dart
jetsclient/lib/routes/jets_route_data.dart
jetsclient/lib/routes/jets_route_information_parser.dart
jetsclient/lib/routes/jets_router_delegate.dart
jetsclient/lib/routes/jets_routes_app.dart
jetsclient/lib/screens/login.dart
jetsclient/lib/screens/registration.dart
jetsclient/pubspec.lock
jetsclient/pubspec.yaml

JetStore Client Define the main app navigation skeleton

---

jets/bridge/bridge.go
jets/rdf/rdf_ast_test.cc
jets/rete/jets_rete_cwrapper.cpp
jets/rete/jets_rete_cwrapper.h

JetStore Server: Add support for native sql date and datetime

---

jetsclient/lib/screens/components/dropdown_form_field.dart
jetsclient/lib/screens/components/form.dart
jetsclient/lib/screens/components/input_text_form_field.dart
jetsclient/lib/screens/components/text_field.dart
jetsclient/lib/screens/registration.dart
jetsclient/lib/utils/form_config.dart

JetStore Client: Fix dropdown functionality, add flex to layout

---

jets/apiserver/sql_stmts.go
jetsclient/lib/screens/screen_delegates/config_delegates.dart

JetStore Client: Fix update mapping to remove on conflict clause

---

Dockerfile.go_bullseye

Fix build: add jets_init.db to image

---

jets/loader/loader.go
jets/server/server.go

JetStore: Add print of raw command line arguments for loader and server

---

.gitignore
jets/run_reports/main.go

JetStore Add run_reports script

---

Dockerfile.rt_bullseye
jets/apiserver/server.go
jets/apiserver/user.go
jetsclient/lib/models/user.dart
jetsclient/lib/screens/components/app_bar.dart
jetsclient/lib/screens/screen_delegates/user_delegates.dart
jetsclient/lib/utils/constants.dart

JetStore Client: Add admin user defined at deployment time

---

jets/apiserver/api_tables.go
jets/apiserver/api_users.go
jets/apiserver/sql_stmts.go
jets/apiserver/user.go
jets/server/jets_schema.json
jetsclient/lib/http_client.dart
jetsclient/lib/routes/jets_router_delegate.dart
jetsclient/lib/routes/jets_routes_app.dart
jetsclient/lib/screens/components/app_bar.dart
jetsclient/lib/screens/components/base_screen.dart
jetsclient/lib/screens/components/data_table.dart
jetsclient/lib/screens/screen_delegates/config_delegates.dart
jetsclient/lib/screens/screen_delegates/user_delegates.dart
jetsclient/lib/utils/constants.dart
jetsclient/lib/utils/data_table_config.dart
jetsclient/lib/utils/form_config.dart
jetsclient/lib/utils/screen_config.dart

JetStore Client Add user administration screen for admin user.

---

jets/apiserver/user.go
jetsclient/lib/screens/screen_delegates/user_delegates.dart

JetStore Client update password policy

---

jetsclient/pubspec.lock

JetStore Upgrade flutter package to latest

---

jets/run_reports/main.go
jetsclient/lib/screens/screen_delegates/user_delegates.dart

JetStore Add process name as substitution variable in run_report

---

jets/schema/schema.go

JetStore Preserve user table when resetting database

---

jetsclient/lib/utils/data_table_config.dart

JetStore Fix pipeline table column offset

---

jets/apiserver/api_tables.go
jets/apiserver/main.go
jets/server/pipeline.go
jets/server/rete.go
jets/server/rete_entity.go
jets/server/table_reader.go

Investigate locking issue

---

jets/apiserver/api_tables.go
jets/bridge/bridge_test.go
jets/server/rete.go
jets/server/table_writer.go

JetStore Clean up debug messages

---

jets/apiserver/api_filekey.go
jets/apiserver/api_tables.go
jets/apiserver/main.go
jets/apiserver/server.go
jets/apiserver/sql_stmts.go
jetsclient/lib/screens/screen_delegates/user_delegates.dart
jetsclient/lib/utils/constants.dart
jetsclient/lib/utils/data_table_config.dart

JetStore Client Add delete user from user Admin page

---

jets/server/pipeline.go
jets/server/process_config.go
jets/server/rete_entity.go
jets/server/rete_input.go

JetStore Fix Allow unmapped value for missing column

---

Dockerfile.go_bullseye
Dockerfile.rt_bullseye

JetStore modify jetstore build to support cloud9 ide

---

jets/apiserver/server.go

JetStore Add serving jets client to api server

---

cdk/jetstore_one/jetstore_one.go

JetStore Make input bucket name defined as env var

---

.github/workflows/jetstore_image_build.yml
Dockerfile.cdk
Dockerfile.rt_bullseye

Update github action to build and push jetstore image

JetStoreOne Add dockerfile for cdk deployment, update github action

---

cdk/bootstrap_cdk/bootstrap_cdk.go
cdk/jetstore_one/jetstore_one.go

JetStoreOne Add env var SECRETS_SUFFIX

---

cdk/bootstrap_aws/bootstrap_aws.go

JetStoreOne make Github role an env var in bootstrap_aws

---

cdk/jetstore_one/jetstore_one.go
cdk/jetstore_one/lambdas/handlers.py

JetStoreOne Pass apiserver url to lambda for http/s

---

cdk/jetstore_one/lambdas/handlers.py

JetStoreOne testing lambda

---

cdk/jetstore_one/jetstore_one.go

JetStore Use http from lambda to elb when tls is used for ui

---

cdk/jetstore_one/jetstore_one.go

JetStoreOne Add elb for lambda when tls is used for ui

---

cdk/jetstore_one/jetstore_one.go

JetStoreOne set correct dns for lambda to register key

---

cdk/jetstore_one/jetstore_one.go

JetStoreOne Make env var for specifying bastion host keypair

---

cdk/jetstore_one/jetstore_one.go

JetStoreOne When creating jetstore bucket, do not fix bucket name

---

jetsclient/lib/utils/form_config.dart

JetStore Fix UI - sort file column in mapping dropdowns

---

jets/loader/loader.go
jetsclient/lib/screens/components/data_table_source.dart
jetsclient/lib/utils/data_table_config.dart

JetStore Adjust data table ui component to display err message

---

jets/apiserver/api_filekey.go

JetStore Fix: Do not issue sql update if no stale keys are identified

---

jets/apiserver/api_filekey.go
jets/loader/loader.go
jets/server/pipeline.go
jets/server/server.go

JetStore Fix Custom Metrics

---

cdk/jetstore_one/jetstore_one.go

JetStoreOne Fix -  build a single sns alarm topic construct

---

cdk/jetstore_one/jetstore_one.go
cdk/vpc_peering/vpc_peering.go

JetStoreOne Add vpc peering github action

---

cdk/jetstore_one/jetstore_one.go

JetStoreOne Add RDS FreeableMemory metric with an associated alarm

---

jetsclient/lib/screens/screen_delegates/config_delegates.dart
jetsclient/lib/utils/constants.dart
jetsclient/lib/utils/data_table_config.dart
jetsclient/lib/utils/form_config.dart

JetStore UI Review start pipeline dialog to filter on source_type

---

jets/loader/loader.go
jets/schema/headers_domainkeys.go
jets/server/process_config.go
jets/server/rete.go
jets/server/rete_entity.go
jets/server/rete_input.go

JetStore Add the domain keys to the rete session

---

jets/apiserver/server.go
jets/schema/headers_domainkeys.go
jets/schema/schema.go
jets/server/rete_input.go
jets/workspace/workspace.go

JetStore Add hashing override to domain key json in  domain_keys_registry

---

cdk/jetstore_one/jetstore_one.go
jets/apiserver/api_purgedata.go
jets/apiserver/main.go
jets/apiserver/server.go

JetStore Add ability to reset domain table on startup

---

jets/loader/loader.go
jets/rdf/r_resources.cc
jets/rdf/r_resources.h
jets/schema/schema.go
jets/server/jets_schema.json
jets/server/pipeline.go
jets/server/process_config.go
jets/server/rete.go
jets/server/rete_input.go
jets/server/table_reader.go
jets/status_update/main.go
jets/workspace/workspace.go

JetStore Add source period info to rdf session

---

jets/compiler/jetrule_context.py
jets/rete/expr.h
jets/rete/expr_op_others.h
jets/rete/expr_op_test.cc
jets/rete/expr_operator_factory.h

JetStore Add age_as_of and age_in_months_as_of rule operators

---

jets/rete/expr_op_others.h
jets/rete/expr_op_test.cc
jets/rete/expr_operator_factory.h
jets/server/rete.go
jets/server/rete_input.go

JetStore Add jets:currentMonthPeriod to jets:State and operator month_period_of #673

---

jets/rete/jets_rete_cwrapper.cpp

JetStore Add error handling when rules are using an invalid operator

---

jets/apiserver/server.go

JetStore UI Add service for file assets/AssetManifest.bin in apiserver

---

jetsclient/lib/utils/data_table_config_impl.dart
jetsclient/lib/utils/form_config_impl.dart

JetStore UI: Put the Input Registry table at bottom of home page

---

cdk/jetstore_one/jetstore_one.go
jets/bridge/bridge.go
jets/rdf/uuid.cc
jets/status_update/delegate/delegate.go
jets/status_update/main.go

JetStore bug: runReport container exist with code 139

---

jets/CMakeLists.txt
jets/rete/expr_op_logics.h
jets/rete/expr_op_test.cc

JetStore Fix greater than operator between double and int

---

jets/datatable/register_domain_table.go

JetStore Fix Remove object_type component to domain table file key

---

Dockerfile.cdk

JetStore CDK Broken awscli install

---

jets/compute_pipes/pipe_transformation_partition_writer.go
jets/cpipes_booter/booter.go

- fix: Add suffix to partition label

Registration

---

cdk/jetstore_one/stack/build_lambdas.go
jets/compute_pipes/actions_common.go
jets/compute_pipes/actions_coordinate_cp.go
jets/compute_pipes/actions_load_files.go
jets/compute_pipes/actions_process_file.go
jets/compute_pipes/actions_s3_utils.go
jets/compute_pipes/actions_start_reducing_cp.go
jets/compute_pipes/actions_start_sharding_cp.go
jets/compute_pipes/column_evaluators.go
jets/compute_pipes/column_evaluators_mapping.go
jets/compute_pipes/compute_pipes.go
jets/compute_pipes/eval_expression.go
jets/compute_pipes/lookup_table_manager.go
jets/compute_pipes/lookup_table_sql.go
jets/compute_pipes/pipe_executor_merge_files.go
jets/compute_pipes/pipe_transformation_partition_writer.go
jets/compute_pipes/pipes_model.go
jets/compute_pipes/pipes_runtime.go
jets/server/jets_schema.json

- [Prepared for full end-to-end in cpipes w/o db reporting needed](https://github.com/artisoft-io/jetstore/commit/14788f63de85631e08a8eecdcd7a72e02e2a1eeb)
- [Added CPIPES Lookup Tables and cleanup](https://github.com/artisoft-io/jetstore/commit/a5110552e1a77dd5477373a3b38b2937acec1b9a)

Prepared for full end-to-end in cpipes w/o db reporting needed

---

jets/compiler/jetrule_compiler.py
jets/datatable/workspace_helper_functions.go
jets/jetrules/rete/rete_meta_store_factory.go
jets/jetrules/rete/rete_meta_store_model.go
jets/update_db/main.go
jets/workspace/compile_workspace.go

https://github.com/artisoft-io/jetstore/issues/1468

Add build directory in workspace for compiled rete metadata #1468

---

jets/datatable/pipeline_start_with_input_registry.go
jets/datatable/register_domain_table.go
jets/datatable/register_file_key_action.go
jets/datatable/utils.go
jets/loader/register_load.go
jets/run_reports/delegate/run_commands.go

JetStore: Fix race condition when starting pipeline automatically

---

.gitignore
jets/compute_pipes/jetrules_rdf.go
jets/compute_pipes/parquet_schema_info.go
jets/compute_pipes/parquet_write_file.go
jets/jsontest/pqarrow_json_test/main.go
jets/jsontest/pqarrow_json_test/output.json
jets/jsontest/pqarrow_test/main.go

JetStore Fix: Add binary type to parquet

---

jets/run_reports/delegate/run_reports.go

JetStore: Fix run_report when updating workspace files

---

jets/awsi/awsi.go
jets/compute_pipes/actions_start_common.go
jets/compute_pipes/actions_start_common_test.go
jets/compute_pipes/actions_start_sharding_cp.go
jets/compute_pipes/pipes_model.go

JetStore: Add conditional_config for pipe transformation
